//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int Id { get; set; }
        public Nullable<int> BookingId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> PersonType { get; set; }
        public Nullable<int> BookStatus { get; set; }
        public string SeatNo { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual MasterValue MasterValue { get; set; }
        public virtual MasterValue MasterValue1 { get; set; }
        public virtual Room Room { get; set; }
    }
}
