//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int Id { get; set; }
        public string HotelName { get; set; }
        public string HotelDescription { get; set; }
        public string HotelRules { get; set; }
        public string CancellationPolicy { get; set; }
        public Nullable<int> HotelType { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string HotelAddress { get; set; }
        public Nullable<int> HotelRating { get; set; }
        public Nullable<int> CityId { get; set; }
        public string PostalCode { get; set; }
        public string Email { get; set; }
        public Nullable<int> PhoneNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual City City { get; set; }
        public virtual User User { get; set; }
        public virtual MasterValue MasterValue { get; set; }
        public virtual User User1 { get; set; }
        public virtual Image Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
