//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int Id { get; set; }
        public string HotelName { get; set; }
        public string HotelDescription { get; set; }
        public string HotelRules { get; set; }
        public string CancellationPolicy { get; set; }
        public Nullable<int> HotelType { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string HotelAddress { get; set; }
        public Nullable<int> HotelRating { get; set; }
        public Nullable<int> CityId { get; set; }
        public string PostalCode { get; set; }
        public string Email { get; set; }
        public Nullable<int> PhoneNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
