//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> RTCId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<double> Ratings { get; set; }
        public string Review1 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MasterValue MasterValue { get; set; }
    }
}
