//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public int Id { get; set; }
        public string RoomCode { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<double> PriceBase { get; set; }
        public Nullable<double> PricePerAdult { get; set; }
        public Nullable<double> PricePerChild { get; set; }
        public Nullable<int> NoOfAdultAllowed { get; set; }
        public Nullable<int> NoOfChildAllowed { get; set; }
        public Nullable<bool> SmokingFlag { get; set; }
        public Nullable<int> AmenitiesId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Aminity Aminity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual MasterValue MasterValue { get; set; }
        public virtual MasterValue MasterValue1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
