//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenFare
    {
        public int Id { get; set; }
        public Nullable<int> ScreenId { get; set; }
        public Nullable<int> FareType { get; set; }
        public Nullable<double> Rate { get; set; }
    
        public virtual MasterValue MasterValue { get; set; }
        public virtual Screen Screen { get; set; }
    }
}
