//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatDesign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeatDesign()
        {
            this.SeatDesignDetails = new HashSet<SeatDesignDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ScreenId { get; set; }
        public Nullable<int> NoOfRows { get; set; }
        public Nullable<int> NoOfColumns { get; set; }
    
        public virtual Screen Screen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatDesignDetail> SeatDesignDetails { get; set; }
    }
}
